In [7]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

url = "https://ngdc.noaa.gov/stp/space-weather/solar-data/solar-indices/sunspot-numbers/american/lists/list_aavso-arssn_daily.txt"
ignore = 26665-26481
datos_todos = np.genfromtxt(url, skip_header=2,  skip_footer=ignore ).astype(int)
columna_tercera = datos_todos[:, 2]
columna_cuarta = datos_todos[:, 3]
dias = np.arange(1, 26479+ 1)






[[1945    1    1   10]
 [1945    1    2    0]
 [1945    1    3    1]
 ...
 [2017    6   28   13]
 [2017    6   29   10]
 [2017    6   30    9]]


In [6]:
#Punto 1
##1.1
x=dias
y=columna_cuarta
frecuencia_muestreo=1 #De los datos uno puede ver que es aproximadamente un día
frecuencias=np.fft.fftfreq(len(y),frecuencia_muestreo)
transformada=np.fft.fft(y)
modulo=np.abs(transformada)
indice_max=np.argmax(modulo)