In [6]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

url = "https://ngdc.noaa.gov/stp/space-weather/solar-data/solar-indices/sunspot-numbers/american/lists/list_aavso-arssn_daily.txt"
ignore = 26665-26481
datos_todos = np.genfromtxt(url, skip_header=2,  skip_footer=ignore )
columna_tercera = datos_todos[:, 2]
columna_cuarta = datos_todos[:, 3]
dias = np.arange(1, 26479+ 1)

print(datos_todos)





[[1.945e+03 1.000e+00 1.000e+00 1.000e+01]
 [1.945e+03 1.000e+00 2.000e+00 0.000e+00]
 [1.945e+03 1.000e+00 3.000e+00 1.000e+00]
 ...
 [2.017e+03 6.000e+00 2.800e+01 1.300e+01]
 [2.017e+03 6.000e+00 2.900e+01 1.000e+01]
 [2.017e+03 6.000e+00 3.000e+01 9.000e+00]]


In [6]:
#Punto 1